# Generated by Django 4.0.6 on 2022-07-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_category_photo_course_photo_course_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(to='system.category'),
        ),
    ]
