# Generated by Django 4.0.6 on 2022-07-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
