from django.urls import path,include
from rest_framework import routers
from .views import (
    home,
    BookListView,
    BookDetailView,
    AuthorListView,
    AuthorDetailView,
    LoanedBooksByUserListView,
    LoanedBooksListView,
    renew_book_librarian,
    AuthorCreateView,
    AuthorUpdate,
    AuthorDelete,
    BookCreateView,
    BookUpdate,
    BookDelete,
    BlogDetailView,
    about,
    dashboard,
    profile,
    # form,
    BlogCreateView,
    BookInstanceCreateView,
    signUpView,
    
    
)
urlpatterns = [
    path('author/create/', AuthorCreateView.as_view(), name='author-create'),
    path('user/register/', signUpView, name='register'),
    path('book/create/', BookCreateView.as_view(), name='book-create'),
    path('blog/create/', BlogCreateView.as_view(), name='blog-create'),
    path('',home,name="catalog"),
    path('dashboard/',dashboard,name="dashboard"),
    path('profile/',profile,name="profile"),
    path('book/loan/', BookInstanceCreateView, name='loan-book'),
    path('about/',about,name="about"),
    # path('form/',form,name="form"),
    path('blog/<slug:slug>/',BlogDetailView.as_view(),name="blog"),
    path('book/list/',BookListView.as_view(),name="books"),
    path('mybooks/',LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('book/<slug:slug>/',BookDetailView.as_view(),name="book"),
    path('author/list/',AuthorListView.as_view(),name="authors"),
    path('books/borrowed/',LoanedBooksListView.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', renew_book_librarian, name='renew-book-librarian'),
    path('book/<slug:slug>/update/', BookUpdate.as_view(), name='book-update'),
    path('book/<slug:slug>/delete/',BookDelete.as_view(), name='book-delete'),
    path('author/<slug:slug>/',AuthorDetailView.as_view(),name="author"),
    path('author/<slug:slug>/update/', AuthorUpdate.as_view(), name='author-update'),
    path('author/<slug:slug>/delete/',AuthorDelete.as_view(), name='author-delete'),
]
