# Generated by Django 4.0.2 on 2022-08-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_singleblog_remove_blog_date_remove_blog_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleblog',
            name='slug',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
