# Generated by Django 4.0.2 on 2022-08-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_singleblog_slug_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogs',
            field=models.ManyToManyField(to='catalog.SingleBlog'),
        ),
    ]
