# Generated by Django 4.0.2 on 2022-08-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_blog_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleblog',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
