# Generated by Django 4.0.2 on 2022-08-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_singleblog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
