# Generated by Django 4.0.2 on 2022-09-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_rename_prices_bookinstance_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='price',
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(blank=True, default=25.5, null=True),
        ),
    ]
