# Generated by Django 4.0.2 on 2022-09-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_adress_skill_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.adress'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.Skill'),
        ),
    ]
