# Generated by Django 4.0.2 on 2022-09-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_alter_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/user.png', upload_to='images/users/'),
        ),
    ]
